import React,{useState}from'react';import{createRoot}from'react-dom/client';import{Activity,Users,CalendarDays,Stethoscope,Pill,FlaskConical,BedDouble,Receipt,FileText,Menu}from'lucide-react';import'./styles.css';
const patients=[['PT-1001','Aarav Sharma','32','Male','Cardiology','Active'],['PT-1002','Priya Verma','27','Female','General Medicine','Active'],['PT-1003','Rohan Patel','46','Male','Orthopedics','Discharged'],['PT-1004','Ananya Singh','38','Female','Neurology','Active']];
const appointments=[['Aarav Sharma','Dr. Raj Mehta','09:30 AM','Confirmed'],['Priya Verma','Dr. Neha Kapoor','10:15 AM','Waiting'],['Rohan Patel','Dr. Vikram Singh','11:00 AM','Confirmed']];
const doctors=[['Dr. Raj Mehta','Cardiologist','14 years','Available'],['Dr. Neha Kapoor','Physician','9 years','Available'],['Dr. Vikram Singh','Orthopedic','12 years','On leave']];
const nav=[['Dashboard',Activity],['Patients',Users],['Appointments',CalendarDays],['Doctors',Stethoscope],['Pharmacy',Pill],['Laboratory',FlaskConical],['Rooms & Beds',BedDouble],['Billing',Receipt],['Medical Records',FileText]];
function App(){const[page,setPage]=useState('Dashboard');const[open,setOpen]=useState(false);const Icon=nav.find(x=>x[0]===page)?.[1]||Activity;return <div className="app"><aside className={open?'side open':'side'}><div className="brand"><Activity/> <b>CareFlow</b><small>Hospital Management</small></div>{nav.map(([n,I])=><button className={page===n?'active':''} onClick={()=>{setPage(n);setOpen(false)}}><I size={18}/>{n}</button>)}</aside><main><header><button className="menu" onClick={()=>setOpen(!open)}><Menu/></button><div><h1><Icon size={24}/>{page}</h1><p>Thursday, September 3, 2026</p></div><div className="user">HN</div></header><section>{page==='Dashboard'?<Dashboard/>:page==='Patients'?<Table title="Patients" heads={['ID','Name','Age','Gender','Department','Status']} rows={patients}/>:page==='Appointments'?<Table title="Appointments" heads={['Patient','Doctor','Time','Status']} rows={appointments}/>:page==='Doctors'?<Table title="Doctors" heads={['Name','Specialization','Experience','Status']} rows={doctors}/>:<Empty title={page}/>}</section></main></div>}
function Dashboard(){return <><div className="welcome"><div><h2>Good morning, Admin 👋</h2><p>Here is today's hospital overview.</p></div><button>+ New appointment</button></div><div className="stats"><Stat t="Total Patients" v="1,248"/><Stat t="Appointments" v="86"/><Stat t="Available Beds" v="42 / 120"/><Stat t="Today's Revenue" v="₹2.84L"/></div><div className="grid"><Table title="Today's appointments" heads={['Patient','Doctor','Time','Status']} rows={appointments}/><div className="card"><h3>Department occupancy</h3>{[['Cardiology',78],['General Medicine',64],['Orthopedics',52],['Neurology',41],['Pediatrics',35]].map(x=><div className="bar"><span>{x[0]}</span><b>{x[1]}%</b><i><em style={{width:x[1]+'%'}}/></i></div>)}</div></div></>}
function Stat({t,v}){return <div className="stat"><span>{t}</span><strong>{v}</strong><small>Updated today</small></div>}
function Table({title,heads,rows}){return <div className="card"><div className="cardhead"><h3>{title}</h3><button>+ Add</button></div><div className="scroll"><table><thead><tr>{heads.map(h=><th>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr>{r.map((c,i)=><td className={i===r.length-1?'status':''}>{c}</td>)}</tr>)}</tbody></table></div></div>}
function Empty({title}){return <div className="empty"><Activity size={44}/><h2>{title}</h2><p>This module is ready for data and API integration.</p></div>}
createRoot(document.getElementById('root')).render(<App/>);